export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'body-leading-blank': [2, 'always'],
    'header-max-length': [2, 'always', 108],
    'footer-leading-blank': [1, 'always'],
    'subject-empty': [2, 'never'],
    'type-empty': [2, 'never'],
    'subject-case': [0],
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'chore',
        'revert',
      ],
    ],
  },
  prompt: {
    types: [
      { value: 'feat', name: '✨ 新功能：新增功能' },
      { value: 'fix', name: '🐛 修复：修复bug' },
      { value: 'docs', name: '📚 文档：更新文档' },
      { value: 'refactor', name: '🔨 重构：代码重构（不新增功能也不修复bug）' },
      { value: 'perf', name: '⚡ 性能：提升性能' },
      { value: 'test', name: '🧪 测试：添加测试' },
      { value: 'chore', name: '🛠 工具：更改构建流程或辅助工具' },
      { value: 'revert', name: '⏪ 回滚：代码回滚' },
      { value: 'style', name: '💄 样式：格式调整（不影响代码运行）' },
    ],
    scopes: ['root', 'client', 'server', 'components', 'utils', 'plugins'],
    allowCustomScopes: true,
    skipQuestions: ['body', 'footerPrefix', 'footer', 'breaking'],
    messages: {
      type: '🔹 请选择提交的类型',
      scope: '📌 请选择影响范围（可选）',
      subject: '✏️ 请简要描述更改',
      body: '📝 详细描述（可选）',
      footer: '🔗 关联的 ISSUE 或者 BREAKING CHANGE 描述（可选）',
      confirmCommit: '✅ 确认提交？',
    },
  },
};
